### PR TITLE
Custom Map Sizes

### PR DESCRIPTION
**Pull request by Shad0wlife**
I'll publish this as a Draft first so code style can be discussed.

The weird custom XML generator was set up to reflect the decompressed xml formatting as much as possible and allow for somewhat memory efficient implementations of larger values. Thus no System.Xml.Serialization.XMLSerializer (which would also add an xml header to the file and try to add namespaces to the root element I believe). Though since all the XML data is passed to the FileDB compressor, the actual effect of the memory saving gets lost I guess.
So feel free to discuss the approach!

Adds the feature to create (empty) maps with custom sizes.
- The new maps are created via "Open" -> "New Map file...".
- In the View that opens, both map size and playable area size can be set by a slider
  - These sliders are limited to increments of 64 and 8 respecitvely due to game limitations
- The a7t and a7te files are now generated by AME and do not get loaded from the game's rda files anymore. The structure of the generated XML has to be checked after game updates.
- As long as the current map is in the moderate region, it can be exported as a mod, but will always target the Old World (not Cape Trelawney)
- A newly created map will have all 4 spawn points inserted near the center. These should not be deleted, as there is currently no way to add them again.

**This PR should only be merged after the RDAExplorer.dll that is used was updated with functional compression.**

### CODE REVIEW

**Comment by jakobharder** [comment]
The looks good in general 👍

Here are a few points I'd change sooner or later: 

- New map button directly opens a new map with default size.
  The slider is instead on the main view, so that you can also change the size afterwards.
- Simplify the playable area. Either leave it out completely or have a slider for the margin, not its size.
- Clicking on export currently freezes for a moment the UI. Should be moved outside of UI thread.
- I'd add a test that creates a new map with a vanilla size and compare that to one of the vanilla maps.

**Comment by Shad0wlife** [comment]
TODO: Async Export, Unit Tests

I'd be curious, should I maybe use FileDBSerializer logic with a Model Class for the XML representation even though that might have a slight loss of performance, but would then use a standardized XML Serializer? I'm definitely open for the idea, since I created the current XML creation logic before I knew that FileDBSerializer has the Model serialization feature.

**Comment by jakobharder** [comment]
> I'd be curious, should I maybe use FileDBSerializer logic with a Model Class for the XML representation even though that might have a slight loss of performance, but would then use a standardized XML Serializer?

I would. It's less code.
And a good way to make sure the editor works well together with custom manual workflows using the FileDBReader inbetween.

**Comment by jakobharder** [comment]
> This PR should only be merged after the RDAExplorer.dll that is used was updated with functional compression.

#19

**Comment by jakobharder** [comment]
> TODO: Async Export, Unit Tests

I would skip async and do that in a separate PR.
It should make it easier to continue to work on other issues without fearing merge conflicts.

**Comment by Shad0wlife** [comment]
Ok. Should I leave the Non-FileDBSerializer a7t code in, until FileDBSerializer has renaming and Tuple(?) capabilities built in?

Also, I'll have to force push to this PR to modify a commit, since I realized that I accidentally uploaded my edited RDAExplorer.dll in one of the commits. Just as a heads up.

**Comment by Shad0wlife** [comment]
Should I keep the copy-pasted nested FileDB data from the game's a7t file, or should I generate that data, even though it does not match byte-by-byte (the content effectively matches, the name tags just get stored in different order).

It's theoretically possible to Unit Test the generated nested data against the original by deconstructing the encoded file, but that feels overkill to me.

Thoughts/Preferences?

**Comment by jakobharder** [comment]
I'd go for the generated data.
We would need that for resized maps anyway.

The unit tests don't have to be against the originals necessarily.
A round trip using only generated would be already good to check if future changes broke something.

**Comment by Shad0wlife** [comment]
The nested generated data is entirely independent of map size, so that wouldn't matter. But sure I can use that just fine, it's simply the first stage of the object to FileDB code that I prepared.

**Comment by jakobharder** [comment]
Up to you. I'm fine merging the current state for now :)

**Comment by Shad0wlife** [comment]
I still need to do the Unit Tests and eventually switch from my custom XML generation to FileDBSerializer as soon as the required features are added to that, but if those things are to be done in separate PRs (the FileDBSerializer especially), then this should be ready for review.

**Pull request merged**
